### ISSUE TITLE
Bookmark feature issue

### ISSUE THREAD

**Issue by costaalex** [gargakshit/unpaprd#4]
The bookmark feature doesn't seem to be working.

**Comment by gargakshit** [comment]
Hello Alex
Currently I am occupied with my exams and college. I will look into the issue as soon as they are over :)

**Comment by costaalex** [comment]
Great. I'm new into Flutter but I'll try to look into it too :))

**Comment by costaalex** [comment]
So, it is keeping the bookmarks after reinstalling, but the problem is that if I quit the app at a certain minute, (for example 14), the next time I open the audiobook, it replays aproximately 15 minutes after compared to the last session.

**Comment by costaalex** [comment]
I found the problem. In the `updateSharedPrefs()` function (components/player.dart), the `position.inSeconds` returns the number of seconds from the beginning of the audio. For minute 2, second 2, `position.inSeconds` will be 112. So it adds to the position 2 times the same thing.
In the function `updateSharedPrefs()`, replace:
`position.inSeconds,`
with
` (position.inSeconds - (position.inMinutes * 60)).toString(),`

**Comment by costaalex** [comment]
The same logic applies to minutes:

` (position.inMinutes - position.inHours * 60).toString(),`
